import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/layout/Sidebar";
import Link from "next/link";
import { Mic } from "lucide-react";



export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by Task Manager",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="md:min-h-screen h-screen bg-background flex overflow-hidden">
          <Sidebar />
          <main className="flex-1 md:pl-64 relative w-full overflow-y-auto h-screen bg-gray-50">
            <div className="max-w-5xl mx-auto p-4 pb-32 md:p-8 md:pb-12 min-h-full ">
              <div className="fixed bottom-10 right-10 z-50">
                <Link href={'#'} >
                  <button className="
                      rounded-full flex items-center justify-center text-white text-xl font-extrabold  w-20 h-20 my-button ">
                    <Mic width="32" height='32' viewBox="0 0 24 24" stroke="currentColor" />
                  </button>
                </Link>
              </div>
              {children}
            </div>
          </main>
        </div>

      </body>
    </html>
  );
}
